# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               cooperad
tagline:             'the dual notion of operad'
description:         'oid'
url:                 http://cooperad.github.io
baseurl:             http://cooperad.github.io
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
